canonical = "en"
locales = "examples/locales"

[[target]]
lang = "typescript"
out = "examples/out/stele.gen.ts"

[[target]]
lang = "swift"
out = "examples/out/Stele.swift"

[[target]]
lang = "store"
out = "examples/out/stele.store.ts"
core = "./stele.gen"

[[target]]
lang = "react"
out = "examples/out/stele.react.ts"
store = "./stele.store"
