canonical = "en"
locales = "examples/locales"

[[target]]
lang = "typescript"
out = "examples/out/stele.gen.ts"

[[target]]
lang = "swift"
out = "examples/out/Stele.swift"

[[target]]
lang = "react"
out = "examples/out/stele.react.ts"
core = "./stele.gen"
